name: Rebuild Dist

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: '!build'
        reaction: '+1'
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      if: steps.check.outputs.triggered == 'true'
      with:
        token: ${{ secrets.PAT }}
    - name: Use Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # 3.9.1
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm run all

    - name: Check for changes
      run: |
        if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
          echo "changes_exist=false" >> $GITHUB_ENV
        else
          echo "changes_exist=true" >> $GITHUB_ENV
        fi

    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
      if: ${{ env.changes_exist == 'true' }}
      with:
        commit_message: ':package: (core): update build files'
